#
# Bareflank Hypervisor
# Copyright (C) 2015 Assured Information Security, Inc.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

os: Visual Studio 2015
platform: x64

#
# Custom environment variables
#
environment:
  global:
    CYG_ROOT: C:\cygwin_bareflank
    CYG_BASH: C:\cygwin_bareflank\bin\bash
    CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
    CYG_PACKAGES: git,make,gcc-core,gcc-g++,nasm,clang,clang++,cmake,python,gettext
    BFPATH: '%PATH%'
    PATH: '%PATH%;C:\Program Files\NASM'

cache:
  - ../cache

#
# Setup Cygwin
#
install:

  #
  # Nasm
  #
  - ps: Start-FileDownload "http://www.nasm.us/pub/nasm/releasebuilds/2.13.03/win64/nasm-2.13.03-installer-x64.exe" -FileName "nasm-installer-x64.exe"
  - nasm-installer-x64.exe /S

  #
  # Cygwin
  #
  - ps: Start-FileDownload "https://cygwin.com/setup-x86_64.exe" -FileName "setup-x86_64.exe"
  - setup-x86_64.exe --quiet-mode --no-shortcuts --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_ROOT%\var\cache\setup" --packages "%CYG_PACKAGES%"

#
# Build
#
build_script:

  #
  # Visual Studio (MSBuild / Static Libraries)
  #
  - mkdir build_msbuild
  - cd build_msbuild
  - cmake -G "Visual Studio 14 2015 Win64" -DENABLE_BUILD_VMM=OFF -DENABLE_BUILD_USERSPACE=OFF -DENABLE_BUILD_TEST=ON ..
  - msbuild /m:3 hypervisor.sln
  - cmake --build . --target test
  - cmake --build . --target test

  #
  # Cygwin (Shared Libraries)
  #
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; mkdir build_cygwin"'
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER/build_cygwin; cmake -DENABLE_BUILD_TEST=ON .."'
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER/build_cygwin; make -j3"'
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER/build_cygwin; make unittest"'
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER/build_cygwin; make unittest"'

#
# No AppVeyor Tests
#
test: off
