os: Visual Studio 2017
platform: x64

#
# Custom environment variables
#
environment:
  global:
    CYG_ROOT: C:\cygwin_bareflank
    CYG_BASH: C:\cygwin_bareflank\bin\bash
    CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
    CYG_PACKAGES: git,make,gcc-core,gcc-g++,nasm,clang,clang++,cmake,wget

test: off

#
# Setup Cygwin
#
install:
  - ps: 'Start-FileDownload "https://cygwin.com/setup-x86_64.exe" -FileName "setup-x86_64.exe"'
  - 'setup-x86_64.exe --quiet-mode --no-shortcuts --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_ROOT%\var\cache\setup" --packages "%CYG_PACKAGES%"'
  - 'copy setup-x86_64.exe %CYG_ROOT%\bin\'

#
# Build Bareflank
#
build_script:
    - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; ./tools/scripts/setup_cygwin.sh --compiler clang --linker $HOME/usr/bin/x86_64-elf-ld.exe"'
    - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; make -j2"'
    - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; make driver_build"'
    
